CREATE DATABASE EventEaseDB;
GO
USE EventEaseDB;
GO

-- VENUE Table 
CREATE TABLE VENUE(
    VENUE_ID INT PRIMARY KEY IDENTITY(1,1),
    VENUE_NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    CAPACITY INT NOT NULL,
    IMAGE_URL VARCHAR(500) NULL
);
GO

-- EVENT Table
CREATE TABLE EVENT(
    EVENT_ID INT PRIMARY KEY IDENTITY(1,1),
    EVENT_NAME VARCHAR(100) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    DESCRIPTION TEXT NULL,
    VENUE_ID INT NOT NULL,
    FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID)
);
GO

-- BOOKINGS Table 
CREATE TABLE BOOKINGS (
    BOOKING_ID INT PRIMARY KEY IDENTITY(1,1),
    BOOKING_DATE DATE NOT NULL,
    EVENT_ID INT NOT NULL,
	VENUE_ID INT NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
	FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID)
);
GO

-- Insert into VENUE and store VENUE_ID
INSERT INTO VENUE (VENUE_NAME, LOCATION, CAPACITY, IMAGE_URL) VALUES
('Luxury Banquet', '789 Elite Rd, Uptown', 300, 'https://example.com/venue3.jpg');
DECLARE @VenueID INT = SCOPE_IDENTITY();
GO

-- Insert into EVENT using the captured VENUE_ID
INSERT INTO EVENT (EVENT_NAME, EVENT_DATE, DESCRIPTION, VENUE_ID) VALUES
('Charity Gala', '2025-12-10', 'Fundraising event with dinner and live performances.', 1);
DECLARE @EventID INT = SCOPE_IDENTITY();
GO

-- Insert sample data into BOOKINGS
INSERT INTO BOOKINGS (BOOKING_DATE, EVENT_ID, VENUE_ID)
VALUES ('2025-11-25', 1, 1);
GO

-- Query select
SELECT * FROM VENUE;
SELECT * FROM EVENT;
SELECT * FROM BOOKINGS;
GO
